//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.ProfessorResearchPapers = new HashSet<ProfessorResearchPaper>();
            this.Scholarships = new HashSet<Scholarship>();
            this.StudentMessages = new HashSet<StudentMessage>();
        }
    
        public int ProfID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string EducationalBackground { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public string Funding { get; set; }
        public string Password { get; set; }

        [DisplayName("Upload File")]
        public string Picture { get; set; }
       
        public HttpPostedFileBase ImageFile { get; set; }
        public string Department { get; set; }
        public Nullable<int> UniID { get; set; }
        public int InterestID { get; set; }
        public int ExpertiseID { get; set; }
    
        public virtual Expertise Expertise { get; set; }
        public virtual Interest Interest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorResearchPaper> ProfessorResearchPapers { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scholarship> Scholarships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMessage> StudentMessages { get; set; }
    }
}
