//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scholarship()
        {
            this.StudentScholarships = new HashSet<StudentScholarship>();
        }
    
        public int ScholarshipID { get; set; }
        public string DegreeName { get; set; }
        public Nullable<int> UniID { get; set; }
        public Nullable<int> ProfID { get; set; }
        public string Subject { get; set; }
        public double PercentageOfScholarship { get; set; }
        public string Session { get; set; }
        public int Seats { get; set; }
        public string MinimumGPA { get; set; }
        public string OtherRequirements { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScholarship> StudentScholarships { get; set; }
    }
}
