//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExpertise
    {
        public int StudentExpertiseID { get; set; }
        public int StudentId { get; set; }
        public int ExpertiseID { get; set; }
        public byte[] Certificate { get; set; }
        public string Institution { get; set; }
    
        public virtual Expertise Expertise { get; set; }
        public virtual Student Student { get; set; }
    }
}
