//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScholarship
    {
        public int StudentScholarshipID { get; set; }
        public Nullable<int> ScholarshipID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Status { get; set; }
    
        public virtual Scholarship Scholarship { get; set; }
        public virtual Student Student { get; set; }
    }
}
